Repository poanetwork/token-wizard, pull requests merged in 2018-04, with the labels that each got.

#761 (Fix) Fix countdown not displaying days
  src/components/invest/index.js
Labels: in progress

#766 (Fix) Update fields in reverse order and endTimes before startTimes
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/manage/utils.spec.js
Labels: awaiting for review

#768 (Fix) Make countdown work when next tier is more than 30 days away
  src/components/invest/index.js
Labels: awaiting for review

#774 (Fix) Use BigNumber in invest page
  src/components/invest/index.js
Labels: awaiting for review

#779 (Fix) Use bigNumber to operate with supply value
  src/components/manage/utils.js
  src/components/stepFour/utils.js
Labels: awaiting for review

#783 (Fix) Remove unnecessary validation
  src/utils/validations.js
  src/utils/validations.spec.js
Labels: in progress

#787 (Feature) Add bulk import for reserved tokens
  src/components/Common/ReservedTokensInputBlock.js
  src/components/Common/ReservedTokensInputBlock.spec.js
  src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
  src/components/stepTwo/StepTwoForm.spec.js
  src/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
  src/utils/alerts.js
  src/utils/processReservedTokens.js
  src/utils/processReservedTokens.spec.js
Labels: awaiting for review

#778 (Fix) Validate whitelist min/max
  src/components/Common/TierBlock.js
  src/components/Common/WhitelistInputBlock.js
  src/components/manage/index.js
  src/components/stepThree/StepThreeForm.js
  src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
  src/utils/constants.js
  src/utils/processWhitelist.js
  src/utils/processWhitelist.spec.js
  src/utils/validations.js
  src/utils/validations.spec.js
Labels: awaiting for review

#798 (Refactor) Migrate invest page to final-form
  src/components/Common/InputField2.js
  src/components/crowdsale/utils.js
  src/components/invest/InvestForm.js
  src/components/invest/InvestForm.spec.js
  src/components/invest/__snapshots__/InvestForm.spec.js.snap
  src/components/invest/index.js
Labels: awaiting for review

#799 (Fix) Accept decimals reserved tokens
  src/components/Common/TierBlock.js
  src/components/Common/TokenDecimals.js
  src/components/Common/TokenDecimals.spec.js
  src/components/Common/TokenName.js
  src/components/Common/TokenName.spec.js
  src/components/Common/TokenTicker.js
  src/components/Common/TokenTicker.spec.js
  src/components/Common/__snapshots__/TokenDecimals.spec.js.snap
  src/components/Common/__snapshots__/TokenName.spec.js.snap
  src/components/Common/__snapshots__/TokenTicker.spec.js.snap
  src/components/manage/__snapshots__/ManageForm.spec.js.snap
  src/components/manage/__snapshots__/ManageTierBlock.spec.js.snap
  src/components/stepTwo/StepTwoForm.js
  src/components/stepTwo/index.js
  src/utils/constants.js
  src/utils/validations.js
  src/utils/validations.spec.js
Labels: affects e2e tests, awaiting for review

#808 (Fix) Summary files fixes
  src/components/stepFour/index.js
  src/stores/ContractStore.js
  src/stores/utils.js
  src/utils/constants.js
Labels: awaiting for review

#809 (Fix) screenshots for verification
  docs/CrowdsaleTokenExt-verify-contract.png
  docs/FlatPricingExt-verify-contract.png
  docs/MintedTokenCappedCrowdsaleExt-verify-contract.png
  docs/ReservedTokensFinalizeAgent-verify-contract.png
Labels: awaiting for review

#810 (Fix) deployment on windows PCs
  package-scripts.js
Labels: awaiting for review

#822 (Fix) Add class 'error' to InputField
  src/components/Common/InputField.js
  src/components/Common/__snapshots__/AddressInput.spec.js.snap
  src/components/Common/__snapshots__/BigNumberInput.spec.js.snap
  src/components/Common/__snapshots__/NumericInput.spec.js.snap
  src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
  src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
Labels: awaiting for review

#825 (Fix) Trigger minCap-supply validation after supply has been changed
  src/components/stepThree/StepThreeForm.js
  src/components/stepThree/index.js
Labels: awaiting for review
