Repository poanetwork/token-wizard, pull requests merged in 2018-06, with the labels that each got.

#935 (Fix) Rename invest
  src/App.js
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application.scss
  src/assets/stylesheets/application/invest.scss
  src/components/Common/AddressInput.spec.js
  src/components/Common/__snapshots__/AddressInput.spec.js.snap
  src/components/contribute/ContributeForm.js
  src/components/contribute/ContributeForm.spec.js
  src/components/contribute/CountdownTimer.js
  src/components/contribute/CountdownTimer.spec.js
  src/components/contribute/QRPaymentProcess.js
  src/components/contribute/__snapshots__/ContributeForm.spec.js.snap
  src/components/contribute/__snapshots__/CountdownTimer.spec.js.snap
  src/components/contribute/constants.js
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/index.js
  src/components/invest/InvestForm.spec.js
  src/stores/ContributeStore.js
  src/stores/CrowdsalePageStore.js
  src/stores/index.js
  src/utils/alerts.js
  src/utils/constants.js
Labels: affects e2e tests, awaiting for review

#937 (Refactoring) collapse deployCrowdsale and deployDutchAuctionCrowdsale to one function
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/manage/DistributeTokensStep.js
  src/components/manage/index.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/components/stepThree/StepThreeFormDutchAuction.js
  src/components/stepTwo/StepTwoForm.js
  src/stores/CrowdsaleStore.js
  src/utils/alerts.js
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#942 (Fix) Wrong tiers' duration calculation
  src/components/manage/index.js
Labels: awaiting for review

#951 (Fix) Validate query strings
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/stores/ContractStore.js
  src/stores/Web3Store.js
  src/stores/index.js
  src/stores/utils.js
  src/utils/alerts.js
  src/utils/blockchainHelpers.js
  src/utils/utils.js
Labels: affects e2e tests, awaiting for review

#952 (Fix) Update events' interfaces
  src/utils/constants.js
Labels: awaiting for review

#953 (Fix) Stats update
  .env.example
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/stats/index.js
  src/utils/blockchainHelpers.js
  src/utils/constants.js
Labels: awaiting for review

#956 Allow whitelist editing even if tier is not editable
  src/components/manage/ManageForm.spec.js
  src/components/manage/ManageTierBlock.js
  src/components/manage/__snapshots__/ManageForm.spec.js.snap
  src/components/manage/index.js
  src/stores/TierStore.js
Labels: awaiting for review

#954 (Fix) Allow min cap edit after crowdsale started
  src/components/crowdsale/utils.js
  src/components/manage/ManageForm.js
  src/components/manage/index.js
  src/utils/utils.js
Labels: awaiting for review

#959 (Refactoring) Support of Proxy for manage page
  src/App.js
  src/components/Home/index.js
  src/components/contribute/index.js
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/stores/utils.js
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#960 (Fix) Dutch auction crowdsale support for new Registry
  .env.example
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/index.js
  src/stores/ContractStore.js
  src/stores/CrowdsaleStore.js
  src/stores/utils.js
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#963 (Fix) Deployment modal columns
  src/components/Common/TxProgressStatus.js
Labels: awaiting for review

#964 (Fix) Get length of all applications
  .env.example
  src/components/stats/index.js
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#967 (Fix) Statistics: maxEthRaised fix in stats
  src/components/stats/index.js
Labels: awaiting for review

#969 (Refactor) getApplicationsInstances method
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#970 (Fix) Dutch auction crowdsale: is_whitelisted flag
  .env.example
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/stores/utils.js
Labels: awaiting for review

#968 (Feature) deployment step: global min cap per tier
  .env.example
  src/components/Common/DutchAuctionBlock.js
  src/components/Common/GlobalMinCap.js
  src/components/Common/TierBlock.js
  src/components/crowdsale/utils.js
  src/components/manage/ManageForm.js
  src/components/manage/ManageForm.spec.js
  src/components/manage/ManageTierBlock.spec.js
  src/components/manage/__snapshots__/ManageForm.spec.js.snap
  src/components/manage/__snapshots__/ManageTierBlock.spec.js.snap
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/constants.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/components/stepThree/StepThreeFormDutchAuction.js
  src/components/stepThree/StepThreeFormMintedCapped.js
  src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
  src/components/stepThree/index.js
  src/stores/DeploymentStore.js
  src/stores/TierStore.js
  src/stores/utils.js
Labels: awaiting for review

#971 (Fix) whitelists for both strategies fix
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/utils.js
Labels: awaiting for review

#972 (Fix) Remove obsolete React state example
  ICO_wizard_state_example.json
Labels: awaiting for review

#973 (Feature) Allow minCap modification from manage page
  src/components/manage/ManageForm.js
  src/components/manage/ManageTierBlock.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/constants.js
  src/components/stepFour/utils.js
  src/components/stepThree/index.js
  src/stores/DeploymentStore.js
Labels: awaiting for review

#979 (Fix) Remove token/sale managers contracts for Dutch Auction
  .env.example
  src/components/manage/index.js
  src/components/stepFour/utils.js
  src/index.js
  src/stores/ContractStore.js
  src/stores/utils.js
Labels: awaiting for review

#981 (Fix) Min cap validate with supply
  src/components/Common/DutchAuctionBlock.js
  src/components/Common/MinCap.js
  src/components/Common/TierBlock.js
  src/components/stepThree/index.js
  src/utils/validations.js
  src/utils/validations.spec.js
Labels: awaiting for review

#983 (Fix) display correct min cap in contribution page
  src/components/crowdsale/utils.js
  src/components/stepFour/utils.js
Labels: awaiting for review

#993 (Fix) Total Raised Funds expressed in scientific notation
  src/components/crowdsale/index.js
Labels: awaiting for review

#992 (Fix) Proxy usage update: support of Dutch Auction
  .env.example
  .gitignore
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/stores/ContractStore.js
  src/stores/CrowdsaleStore.js
  src/stores/utils.js
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#991 (Feature) toBigNumber signature change
  package-lock.json
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stats/index.js
  src/components/stepFour/utils.js
  src/utils/utils.js
  src/utils/validations.js
  test/utils/validations.spec.js
Labels: awaiting for review, enhancement

#990 (Bug) show the initial and end parts of exec-id at invest page
  package.json
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application/contribute.scss
  src/components/contribute/index.js
  src/utils/utils.js
  test/utils/utils.spec.js
Labels: awaiting for review

#995 (Fix) Finalize Dutch crowdsale before it has ended
  .env.example
  src/components/stepFour/utils.js
  src/stores/CrowdsaleStore.js
  src/stores/utils.js
Labels: awaiting for review
