Repository poanetwork/token-wizard, pull requests merged in 2018-03, with the labels that each got.

#633 (Fix) Validate Invest Input
  src/components/invest/index.js
Labels: awaiting for review

#631 (Fix) Restrict token mantissa to decimals
  src/components/Common/InputField.js
  src/components/Common/NumericInput.js
  src/components/Common/NumericInput.spec.js
  src/components/Common/ReservedTokensInputBlock.js
  src/components/Common/ReservedTokensInputBlock.spec.js
  src/components/Common/__snapshots__/NumericInput.spec.js.snap
  src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
  src/components/stepThree/index.js
  src/components/stepTwo/index.js
  src/stores/TierStore.js
  src/stores/TokenStore.js
  src/utils/constants.js
  src/utils/utils.js
  src/utils/utils.spec.js
Labels: awaiting for review

#638 (Fix) 'End date' modifiable after crwodsale was finalized
  src/components/manage/index.js
Labels: awaiting for review

#646 (Fix) Fix gas price validation
  src/components/stepThree/index.js
Labels: awaiting for review

#639 (Feature) Bulk import whitelist
  ICO_wizard_state_example.json
  package-lock.json
  package.json
  src/components/Common/WhitelistInputBlock.js
  src/components/Common/WhitelistItem.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/utils.js
  src/components/stepThree/CrowdsaleBlock.js
  src/components/stepThree/index.js
  src/stores/TierStore.js
  src/utils/constants.js
  src/utils/utils.js
Labels: awaiting for review

#653 Move 'Upload CSV' button and add icon
  package-lock.json
  package.json
  src/components/Common/WhitelistInputBlock.js
  src/index.js
Labels: awaiting for review

#650 (Fix) Don't continue to step 4 if min cap is not valid
  src/components/stepThree/index.js
  src/stores/TierStore.js
  src/stores/TierStore.spec.js
  src/utils/constants.js
Labels: awaiting for review

#662 (Fix) Disable finalize button
  src/components/manage/index.js
  src/utils/alerts.js
Labels: awaiting for review

#656 (Feature) Indicate to user how many addresses were imported to the whitelist
  src/components/Common/WhitelistInputBlock.js
  src/utils/alerts.js
  src/utils/processWhitelist.js
  src/utils/processWhitelist.spec.js
Labels: awaiting for review

#664 (Fix) Set deploymentStep when starting step four
  src/components/stepFour/index.js
Labels: awaiting for review

#676 (Fix) Fix token's name max length
  src/utils/utils.js
  src/utils/utils.spec.js
Labels: awaiting for review

#654 (Fix) Metamask not being called
  package-lock.json
  package.json
  src/components/Common/BigNumberInput.js
  src/components/Common/BigNumberInput.spec.js
  src/components/Common/__snapshots__/BigNumberInput.spec.js.snap
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/utils.js
  src/components/stepThree/CrowdsaleBlock.js
  src/components/stepThree/CrowdsaleBlock.spec.js
  src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
  src/components/stepThree/index.js
  src/components/stepThree/utils.js
  src/components/stepThree/utils.spec.js
  src/components/stepTwo/index.js
  src/stores/StepThreeValidationStore.js
  src/stores/TierCrowdsaleListStore.js
  src/stores/TierStore.js
  src/stores/index.js
  src/stores/utils.js
  src/utils/constants.js
  src/utils/utils.js
Labels: awaiting for review

#684 (Fix) link to Deployment Time & Gas in README
  README.md
Labels: awaiting for review

#687 (Fix) Add airbnb JS shims
  package-lock.json
  package.json
  src/index.js
Labels: awaiting for review

#681 (Refactor) remove obsolete contracts methods and derivatives
  src/components/crowdsale/utils.js
  src/components/invest/index.js
  src/stores/CrowdsalePageStore.js
  src/utils/alerts.js
Labels: awaiting for review

#672 (Fix) Add address to whitelist in manage screen
  package-lock.json
  package.json
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application/manage.scss
  src/assets/stylesheets/application/steps/whitelist.scss
  src/components/Common/WhitelistInputBlock.js
  src/components/Common/WhitelistItem.js
  src/components/crowdsale/index.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/utils.js
  src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
  src/components/stepThree/index.js
  src/stores/TierStore.js
  src/stores/TierStore.spec.js
  src/utils/constants.js
Labels: awaiting for review

#683 (Fix) Countdown timer
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application/invest.scss
  src/components/crowdsale/utils.js
  src/components/invest/index.js
  src/stores/CrowdsalePageStore.js
  src/stores/CrowdsalePageStore.spec.js
  src/utils/constants.js
Labels: awaiting for review

#689 (Fix) Supply calculus for invest page
  src/components/invest/index.js
Labels: awaiting for review

#680 (Refactor) Add react-web3
  package.json
  src/App.js
  src/components/Common/NoWeb3.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/index.js
  src/react-web3/Web3Provider.js
  src/react-web3/index.js
  src/utils/microservices.js
Labels: awaiting for review

#691 (Fix) Wrong decimal count invest page
  src/components/stepThree/index.js
Labels: awaiting for review

#693 (Fix) Prevent deployment if minCap isn't valid
  src/components/stepThree/index.js
Labels: awaiting for review

#695 Revert "(Fix) Prevent deployment if minCap isn't valid"
  src/components/stepThree/index.js
Labels: in progress

#697 (Fix) unify dev and prod interfaces
  src/components/Common/TxProgressStatus.js
  src/components/stepFour/index.js
Labels: affects e2e tests, awaiting for review

#692 (Refactor) Remove contract type checks
  src/components/Common/ReservedTokensInputBlock.spec.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/components/invest/index.js
  src/components/manage/index.js
  src/components/manage/utils.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
  src/components/stepOne/index.js
  src/components/stepThree/index.js
  src/components/stepThree/utils.spec.js
  src/stores/ContractStore.js
  src/utils/constants.js
Labels: awaiting for review

#665 (Feature) Add 'Clear all' button to reserved tokens
  src/components/Common/ReservedTokensInputBlock.js
  src/components/Common/ReservedTokensInputBlock.spec.js
  src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
  src/components/stepTwo/index.js
  src/stores/ReservedTokenStore.js
  src/utils/alerts.js
Labels: awaiting for review

#701 (Fix) display wallet address in all tiers
  src/components/stepFour/index.js
Labels: awaiting for review

#700 (Fix) Unprecise rate
  src/components/crowdsale/index.js
  src/components/manage/utils.js
Labels: awaiting for review

#709 (Fix) Cast to bigNumber values returned by contracts
  src/components/crowdsale/utils.js
Labels: awaiting for review

#703 (Chore) Add HMR
  src/index.js
  src/react-web3/Web3Provider.js
Labels: awaiting for review

#685 (Feature) Warning on account switch
  src/App.js
  src/components/IncompleteDeploy.js
  src/components/stepFour/index.js
  src/stores/DeploymentStore.js
  src/utils/cancelDeploy.js
Labels: awaiting for review

#699 (Fix) minCap validation before continue
  src/components/Common/NumericInput.js
  src/components/Common/NumericInput.spec.js
  src/components/Common/TxProgressStatus.js
  src/components/stepThree/index.js
Labels: awaiting for review

#704 (Fix) Support long token name on invest
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application/invest.scss
  src/components/invest/index.js
Labels: awaiting for review

#710 (Feature) Add bulk delete for whitelists
  src/components/Common/WhitelistInputBlock.js
  src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
  src/stores/TierStore.js
  src/stores/TierStore.spec.js
  src/utils/alerts.js
Labels: awaiting for review

#718 (Fix) Change min cap description
  src/components/stepThree/index.js
Labels: awaiting for review

#725 (Fix) Scrollable list of crowdsales
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application/flex-table.scss
  src/assets/stylesheets/application/home/crowdsale-modal.scss
Labels: awaiting for review

#702 (Fix) walletAddress validation in stepThree
  src/components/Common/AddressInput.js
  src/components/Common/AddressInput.spec.js
  src/components/Common/__snapshots__/AddressInput.spec.js.snap
  src/components/stepThree/index.js
  src/stores/TierStore.js
  src/utils/utils.js
Labels: awaiting for review

#719 (Chore) Include final form in step two
  package-lock.json
  package.json
  src/components/Common/InputField2.js
  src/components/Common/TokenDecimals.js
  src/components/Common/TokenName.js
  src/components/Common/TokenTicker.js
  src/components/stepTwo/StepTwoForm.js
  src/components/stepTwo/StepTwoForm.spec.js
  src/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
  src/components/stepTwo/index.js
  src/stores/TokenStore.js
  src/utils/utils.js
  src/utils/utils.spec.js
  src/utils/validations.js
  src/utils/validations.spec.js
Labels: awaiting for review

#720 (Fix) Stop countdown if crowdsale is finalized
  src/components/invest/CountdownTimer.js
  src/components/invest/CountdownTimer.spec.js
  src/components/invest/__snapshots__/CountdownTimer.spec.js.snap
  src/components/invest/index.js
Labels: awaiting for review

#736 (Refactor) Use ReservedTokensInputBlock inside final-form
  src/components/stepTwo/StepTwoForm.js
  src/components/stepTwo/StepTwoForm.spec.js
  src/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
  src/components/stepTwo/index.js
Labels: awaiting for review
