Repository poanetwork/token-wizard, pull requests merged in 2018-09, with the labels that each got.

#1120 (Feature) Add ABI-Encoded params for Proxy Contracts
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
Labels: awaiting for review

#1123 (Feature) Add proxy name, compiler version and optimization info to publish page
  src/components/stepFour/constants.js
  src/components/stepFour/index.js
  src/utils/constants.js
Labels: awaiting for review

#1117 (Bug) Dutch- Publish page: uploaded file'Auth-os_addresses.txt' contains wrong names of contracts
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
Labels: awaiting for review, low priority, migration to auth-os

#1121 (Feature) Source code of Proxy smart-contract should be added to zip archive for download
  src/components/stepFour/index.js
Labels: awaiting for review

#1104 (Bug) Keep data between the steps (Integration Branch)
  package-lock.json
  package.json
  src/App.js
  src/components/Common/ButtonContinue.js
  src/components/Common/DutchAuctionBlock.js
  src/components/Common/TierBlock.js
  src/components/Home/index.js
  src/components/contribute/index.js
  src/components/manage/index.js
  src/components/stepFour/index.js
  src/components/stepOne/index.js
  src/components/stepThree/GasPriceInput.js
  src/components/stepThree/StepThreeFormDutchAuction.js
  src/components/stepThree/StepThreeFormMintedCapped.js
  src/components/stepThree/index.js
  src/components/stepTwo/StepTwoForm.js
  src/components/stepTwo/index.js
  src/stores/ContractStore.js
  src/stores/CrowdsaleStore.js
  src/stores/DeploymentStore.js
  src/stores/GasPriceStore.js
  src/stores/GeneralStore.js
  src/stores/ReservedTokenStore.js
  src/stores/TierStore.js
  src/stores/TokenStore.js
  src/stores/Web3Store.js
  src/stores/index.js
  src/utils/alerts.js
  src/utils/blockchainHelpers.js
  src/utils/constants.js
  src/utils/utils.js
  test/components/Common/__snapshots__/TierBlock.spec.js.snap
  test/components/manage/__snapshots__/ManageForm.spec.js.snap
  test/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
Labels: awaiting for review, medium priority, migration to auth-os

#1125 (Feature) metadata should be added to zip archive for download
  src/components/stepFour/utils.js
Labels: awaiting for review

#1133 (Fix) Tests for Home Component
  src/stores/utils.js
  test/components/Home/index.spec.js
Labels: awaiting for review

#1142 (Refactoring) Duplicated line of code in master
  src/components/stepOne/index.js
Labels: awaiting for review

#1141 (Feature) Extract the version of solc compiler from Truffle
  .travis.yml
  package-scripts.js
  package.json
  scripts/getDutchSolcVersion.sh
  scripts/getMintedCappedSolcVersion.sh
  scripts/helpers/deployContract.js
  scripts/helpers/utils.js
  scripts/moveSolcVersionOutput.js
  scripts/moveTruffleConfig.js
  src/components/stepFour/constants.js
  src/components/stepFour/index.js
  src/components/stepFour/utils.js
Labels: awaiting for review

#1152 (Bug) There is no Proxy contract address in zip archive (Minted capped only)
  src/components/stepFour/utils.js
Labels: awaiting for review

#1146 (UI bug) Unfriendly warning at the landing page
  src/App.js
  src/components/Common/ButtonContinue.js
  src/components/Common/CrowdsalesList.js
  src/components/Crowdsales/CrowdsaleEmptyList.js
  src/components/Crowdsales/index.js
  src/components/Home/ChooseCrowdsale.js
  src/components/Home/CreateCrowdsale.js
  src/components/Home/index.js
  src/components/Home/utils.js
  src/components/StepOne/StrategyItem.js
  src/components/StepOne/index.js
  src/components/index.js
  src/stores/ContractStore.js
  src/stores/Web3Store.js
  src/utils/alerts.js
  src/utils/blockchainHelpers.js
  src/utils/errors.js
  src/utils/strategies.js
  src/utils/utils.js
  test/components/Common/CrowdsalesList.spec.js
  test/components/Common/__snapshots__/CrowdsalesList.spec.js.snap
  test/components/Crowdsales/CrowdsaleEmptyList.spec.js
  test/components/Crowdsales/__snapshots__/CrowdsaleEmptyList.spec.js.snap
  test/components/Crowdsales/__snapshots__/index.spec.js.snap
  test/components/Crowdsales/index.spec.js
  test/components/Home/ChooseCrowdsale.spec.js
  test/components/Home/CreateCrowdsale.spec.js
  test/components/Home/__snapshots__/ChooseCrowdsale.spec.js.snap
  test/components/Home/__snapshots__/CreateCrowdsale.spec.js.snap
  test/components/Home/__snapshots__/index.spec.js.snap
  test/components/Home/index.spec.js
  test/components/StepOne/StrategyItem.spec.js
  test/components/StepOne/__snapshots__/StrategyItem.spec.js.snap
  test/components/StepOne/__snapshots__/index.spec.js.snap
  test/components/StepOne/index.spec.js
  test/utils/utils.spec.js
Labels: awaiting for review

#1157 (Fix) Reserved Token Addresses CSV import
  src/components/Common/ReservedTokensInputBlock.js
Labels: Step2-TokenSetup

#1160 (Bug) New design-Home page: unhandled exception in browser's console if wallet isn't installed
  src/App.js
  src/components/Crowdsales/index.js
  src/components/Home/utils.js
  src/components/StepOne/index.js
  src/index.js
  src/stores/Web3Store.js
  src/utils/blockchainHelpers.js
Labels: awaiting for review

#1161 (Fix) Decimals validation for reserved tokens
  src/components/Common/ReservedTokensInputBlock.js
  src/components/StepTwo/StepTwoForm.js
  test/components/Common/ReservedTokensInputBlock.spec.js
  test/components/Common/__snapshots__/CrowdsalesList.spec.js.snap
  test/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
  test/components/Crowdsales/__snapshots__/index.spec.js.snap
  test/components/StepTwo/__snapshots__/StepTwoForm.spec.js.snap
Labels: awaiting for review
