Repository poanetwork/token-wizard, pull requests merged in 2018-08, with the labels that each got.

#1066 (Fix) Handle hardCap in Contribute Page
  src/assets/stylesheets/application.css
  src/assets/stylesheets/application/contribute.scss
  src/components/contribute/ContributeForm.js
  src/components/contribute/CountdownTimer.js
  src/components/contribute/index.js
  src/components/crowdsale/utils.js
  test/components/contribute/ContributeForm.spec.js
  test/components/contribute/CountdownTimer.spec.js
  test/components/contribute/__snapshots__/ContributeForm.spec.js.snap
  test/components/contribute/__snapshots__/CountdownTimer.spec.js.snap
Labels: awaiting for review

#1065 (Bug) Minted, Dutch: Whitelisted addresses are not initialized if list length > 60
  src/components/Common/WhitelistInputBlock.js
  src/stores/TierStore.js
  src/utils/alerts.js
  src/utils/constants.js
  src/utils/processWhitelist.js
Labels: awaiting for review

#1073 (Fix) Investors incorrect maxCap
  package.json
  src/components/Common/DutchAuctionBlock.js
  src/components/Common/TierBlock.js
  src/components/Common/WhitelistInputBlock.js
  src/components/crowdsale/utils.js
  src/components/manage/index.js
  src/components/stepFour/index.js
  src/components/stepTwo/index.js
  src/stores/DeploymentStore.js
  src/utils/alerts.js
  src/utils/blockchainHelpers.js
  src/utils/processWhitelist.js
  test/utils/helpers/whitelist-addresses.json
  test/utils/processWhitelist.spec.js
Labels: awaiting for review

#1096 (Fix) Kovan support in TW 2.0
  .env.example
Labels: awaiting for review

#1099 (Fix) Rinkeby support in TW 2.0
  .env.example
Labels: awaiting for review

#1100 (Fix) POA Core support in TW 2.0
  .env.example
Labels: awaiting for review

#1070 (Bug) Keep data between the steps (Step 1)
  src/App.js
  src/components/Common/ButtonContinue.js
  src/components/Home/index.js
  src/components/stepOne/index.js
  src/stores/ContractStore.js
  src/stores/CrowdsaleStore.js
  src/stores/DeploymentStore.js
  src/stores/GasPriceStore.js
  src/stores/GeneralStore.js
  src/stores/ReservedTokenStore.js
  src/stores/index.js
  src/utils/blockchainHelpers.js
  src/utils/utils.js
Labels: awaiting for review, medium priority, migration to auth-os

#1105 (Fix) Ropsten addresses
  .env.example
Labels: awaiting for review

#1106 (Fix) Add invalidCrowdsaleProxyAlert
  src/components/contribute/index.js
  src/components/crowdsale/index.js
  src/components/manage/index.js
  src/utils/alerts.js
  src/utils/utils.js
Labels: awaiting for review

#1112 (Fix) Update screenshot for StateOfTheDapps
  docs/TW_StateOfTheDapps.png
Labels: in progress

#1081 (Bug) Keep data between the steps (Step 3)
  src/components/Common/ButtonContinue.js
  src/components/Common/DutchAuctionBlock.js
  src/components/Common/TierBlock.js
  src/components/stepThree/GasPriceInput.js
  src/components/stepThree/StepThreeFormDutchAuction.js
  src/components/stepThree/StepThreeFormMintedCapped.js
  src/components/stepThree/index.js
  src/stores/GeneralStore.js
  src/stores/TierStore.js
  src/stores/Web3Store.js
  src/utils/constants.js
  src/utils/utils.js
  test/components/manage/__snapshots__/ManageForm.spec.js.snap
  test/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
Labels: awaiting for review, medium priority, migration to auth-os

#1108 (Fix) crowdsale config should support exec-id and address of proxy as well
  src/components/Common/config.js
  src/components/crowdsale/index.js
  src/components/crowdsale/utils.js
  src/utils/utils.js
Labels: awaiting for review

#1097 (Bug) Keep data between the steps (Step 4 - Publish && Step 5 - Contribution Page)
  src/components/stepFour/index.js
  src/components/stepThree/GasPriceInput.js
  src/components/stepThree/index.js
  src/stores/GeneralStore.js
  src/stores/Web3Store.js
  src/utils/alerts.js
  src/utils/blockchainHelpers.js
  test/components/manage/__snapshots__/ManageForm.spec.js.snap
Labels: awaiting for review, medium priority, migration to auth-os

#1116 (Feature) Add dockerfile
  Dockerfile
Labels: awaiting for review, low priority

#1103 (Bug) Keep data between the steps (Manage Page)
  src/components/Home/index.js
  src/components/manage/index.js
  src/components/stepFour/index.js
  src/utils/blockchainHelpers.js
  src/utils/utils.js
Labels: awaiting for review, medium priority, migration to auth-os

#1115 (Feature) add source code of Proxy smart-contract to Publish page
  src/components/stepFour/index.js
Labels: awaiting for review
